---
title: "XC Analysis"
author: "Samuel Ivanecky"
date: "2023-09-12"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=24, fig.height=16) 

# Code to generate line item performances from TFRRS.
library(tidymodels)
library(httr)
library(jsonlite)
library(RPostgreSQL)
library(DBI)
library(reshape2)
library(stringr)
library(stringi)
library(yaml)
library(rvest)
library(kit)
library(ggthemes)
library(ggridges)
library(ggrepel)
library(ggpubr)
library(zoo)
library(gt)
library(gtExtras)
library(data.table)
library(tidytable)
library(dplyr)
library(fuzzyjoin)
library(stringdist)

# Source file for functions
source("/Users/samivanecky/git/runneR/scrapeR/Scraping_Fxns.R")
source("/Users/samivanecky/git/runneR/scrapeR/meetScrapingFxns.R")

# Read connection data from yaml
pg.yml <- read_yaml("/Users/samivanecky/git/postgres.yaml")

# Connect to database
pg <- dbConnect(
  RPostgres::Postgres(),
  host = pg.yml$host,
  user = pg.yml$user,
  db = pg.yml$database,
  port = pg.yml$port
)

reformatTimes <- function(mark) {
  sec <- str_pad(round((mark %% 60), 2), width = 5, side = "left", pad = "0")
  min <- floor(mark / 60)
  min <- ifelse(min == 0, "", min)
  time <- paste0(min, ":", sec)
  return(time)
}
```

# Query Data
## XC Results
### Ind
```{r}
ind <- dbGetQuery(pg, 
"

select
  *
from 
  xc_ind_dets

")
```

### Team
```{r}
team <- dbGetQuery(pg, 
"

select
  *
from 
  xc_team_dets

")
```

## Rankings
### Historic
#### Regional
```{r}
reg_rnk_h <- dbGetQuery(pg, 
"

select
  *
from 
  historic_xc_regional_rankings

")
```

```{r}
reg_rnk_c <- dbGetQuery(pg, 
"

select
  *
from 
  xc_reg_rank_current

")
```

#### National
```{r}
nat_rnk_h <- dbGetQuery(pg, 
"

select
  *
from 
  historic_xc_national_rankings

")
```

```{r}
nat_rnk_c <- dbGetQuery(pg, 
"

select 
  *
from 
  xc_nat_rank_current

")
```

# Individual Season Analysis
## Aggregate Individual Data
```{r warning=FALSE}
ind_agg <- ind %>%
  group_by(
    NAME, TEAM, year, gender, race_distance
  ) %>%
  summarise(
    avg_pl = mean(PL, na.rm = T),
    best_pl = min(PL, na.rm = T),
    worst_pl = max(PL, na.rm = T),
    avg_time = mean(numeric_time, na.rm = T),
    best_time = min(numeric_time, na.rm = T),
    worst_time = min(numeric_time, na.rm = T),
    avg_time_behind_winner = mean(time_behind_winner, na.rm = T),
    n_races = n_distinct(MEET_DT)
  ) %>%
  filter(
    !is.na(NAME) & NAME != ""
  )

# # Remove any instances of only one race
# ind_agg <- ind_agg %>%
#   filter(
#     n_races > 1
#   )

# Subset to only relevant distance / gender combos
ind_agg <- ind_agg %>%
  filter(
    ( gender == "M" & race_distance %in% c("8k", "10k") ) | ( gender == "F" & race_distance %in% c("5k", "6k") )
  )
```

# Regional Rankings
## Format Data
```{r}
# Melt current regional rankings
regional_rankings_current <- reg_rnk_c %>%
  select(
    Team, region, gender, div, Week..1, Week..2, Week..3, Week..4, Week..5, Week..6
  ) %>%
  rename(
    `1` = Week..1,
    `2` = Week..2,
    `3` = Week..3, 
    `4` = Week..4,
    `5` = Week..5, 
    `6` = Week..6
  ) %>%
  reshape2::melt(
    id.vars = c("Team", "region", "div", "gender"), variable.name = "week", value.name = "ranking"
  ) %>%
  mutate(
    week = as.numeric(week)
  )
```

## Plots
### Division 1
#### Women
```{r}
# Set max week
mx_wk <- 4

# Get final points for labeling sake
final_pts <- regional_rankings_current %>%
  filter( 
    gender == "F" & div == "D1" & !is.na(ranking)
  ) %>%
  group_by(
    Team
  ) %>%
  filter(
    week == 4
  )

regional_rankings_current %>%
  filter( 
    gender == "F" & div == "D1" & !is.na(ranking)
  ) %>%
  ggplot(aes(week, ranking, color = Team, group = Team)) +
  geom_point() +
  geom_line() +
  geom_text(data = final_pts, aes(label = Team, x = week, y = ranking), hjust = 1, vjust = 0) +
  cfbplotR::scale_color_cfb() +
  ggplot2::labs(
    x = "Week",
    y = "Regional Ranking",
    caption = "",
    title = "NCAA XC Regional Ranking by Week - D1 Women",
    subtitle = "Unranked weeks are not shown."
  ) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    aspect.ratio = 9 / 16,
    legend.position = "none",
    axis.text.x = element_text(face = "italic"),
    axis.text.y = element_text(face = "italic"),
    plot.title = ggplot2::element_text(size = 30, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    text = element_text(size=20, face = "bold"),
  ) +
  facet_wrap(
    region ~ ., nrow = 2
  )
```


```{r}
reg_rnk_c %>%
  filter( 
    gender == "M" & div == "D2" & !is.na(Week..5)
  ) %>%
  mutate(
    Preseason = case_when(
      is.na(Preseason) ~ 16, 
      T ~ Preseason
    )
  ) %>%
  ggplot(aes(Preseason, Week..4, color = Team, group = Team)) +
  geom_point(size = 6) +
  geom_segment(aes(x=Preseason, xend=Week..4, y=Week..4, yend=Week..4), size = 2,
               arrow = arrow(length = unit(0.5, "cm"))) +
  scale_x_reverse() +
  geom_text(aes(label = Team, x = Week..4, y = Week..4), hjust = -0.25, vjust = 1.5, size = 4) +
  scale_y_continuous(breaks = unique(reg_rnk_c$Week..1)) +
  scale_x_continuous(breaks = unique(reg_rnk_c$Week..1)) +
  cfbplotR::scale_color_cfb() +
  ggplot2::labs(
    x = "Ranking Movement",
    y = "Current Ranking",
    caption = "",
    title = "NCAA XC Regional Ranking Movement from Preseason - D2 Men",
    subtitle = "Unranked preseason shown as '16'."
  ) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    aspect.ratio = 9 / 16,
    legend.position = "none",
    axis.text.x = element_text(face = "italic"),
    axis.text.y = element_text(face = "italic"),
    plot.title = ggplot2::element_text(size = 30, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    text = element_text(size=20, face = "bold"),
  ) +
  facet_wrap(
    region ~ .
  )
```

#### Men
```{r}
# Get final points for labeling sake
final_pts <- regional_rankings_current %>%
  filter( 
    gender == "M" & div == "D1" & !is.na(ranking)
  ) %>%
  group_by(
    Team
  ) %>%
  filter(
    week == 4
  )

regional_rankings_current %>%
  filter( 
    gender == "M" & div == "D1" & !is.na(ranking)
  ) %>%
  ggplot(aes(week, ranking, color = Team, group = Team)) +
  geom_point() +
  geom_line() +
  geom_text(data = final_pts, aes(label = Team, x = week, y = ranking), hjust = 1, vjust = 0) +
  cfbplotR::scale_color_cfb() +
  ggplot2::labs(
    x = "Week",
    y = "Regional Ranking",
    caption = "",
    title = "NCAA XC Regional Ranking by Week - D1 Men",
    subtitle = "Unranked weeks are not shown."
  ) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    aspect.ratio = 9 / 16,
    legend.position = "none",
    axis.text.x = element_text(face = "italic"),
    axis.text.y = element_text(face = "italic"),
    plot.title = ggplot2::element_text(size = 30, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    text = element_text(size=20, face = "bold"),
  ) +
  facet_wrap(
    region ~ ., nrow = 2
  )
```

# National Rankings
## Format Data
```{r}
# Melt data
national_rankings_current <- nat_rnk_c %>%
  select(
    Team, gender, div, Week..1, Week..2, Week..3, Week..4, Week..5, Week..6
  ) %>%
  rename(
    `1` = Week..1,
    `2` = Week..2,
    `3` = Week..3, 
    `4` = Week..4,
    `5` = Week..5, 
    `6` = Week..6
  ) %>%
  reshape2::melt(
    id.vars = c("Team", "div", "gender"), variable.name = "week", value.name = "ranking"
  ) %>%
  mutate(
    week = as.numeric(week)
  )
```

## Plots
### D1 Women
```{r}
# Set max week
mx_wk <- 4

# Get final points for labeling sake
final_pts <- national_rankings_current %>%
  filter( 
    gender == "F" & div == "D1" & !is.na(ranking)
  ) %>%
  group_by(
    Team
  ) %>%
  filter(
    week == 4
  )

national_rankings_current %>%
  filter( 
    gender == "F" & div == "D1" & !is.na(ranking)
  ) %>%
  ggplot(aes(week, ranking, color = Team, group = Team)) +
  geom_point() +
  geom_line() +
  geom_text(data = final_pts, aes(label = Team, x = week, y = ranking), hjust = 1, vjust = 0) +
  cfbplotR::scale_color_cfb() +
  ggplot2::labs(
    x = "Week",
    y = "National Ranking",
    caption = "",
    title = "NCAA XC National Ranking by Week - D1 Women",
    subtitle = "Unranked weeks are not shown."
  ) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    aspect.ratio = 9 / 16,
    legend.position = "none",
    axis.text.x = element_text(face = "italic"),
    axis.text.y = element_text(face = "italic"),
    plot.title = ggplot2::element_text(size = 30, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    text = element_text(size=20, face = "bold"),
  )
```

### D2 Women
```{r}
# Set max week
mx_wk <- 5

# Get final points for labeling sake
final_pts <- national_rankings_current %>%
  filter( 
    gender == "F" & div == "D2" & !is.na(ranking)
  ) %>%
  group_by(
    Team
  ) %>%
  filter(
    week == mx_wk
  )

national_rankings_current %>%
  filter( 
    gender == "F" & div == "D2" & !is.na(ranking)
  ) %>%
  ggplot(aes(week, ranking, color = Team, group = Team)) +
  geom_point() +
  geom_line() +
  geom_text(data = final_pts, aes(label = Team, x = week, y = ranking), hjust = 1, vjust = 0) +
  cfbplotR::scale_color_cfb() +
  ggplot2::labs(
    x = "Week",
    y = "National Ranking",
    caption = "",
    title = "NCAA XC National Ranking by Week - D2 Women",
    subtitle = "Unranked weeks are not shown."
  ) +
  ggplot2::theme_minimal() +
  ggplot2::theme(
    aspect.ratio = 9 / 16,
    legend.position = "none",
    axis.text.x = element_text(face = "italic"),
    axis.text.y = element_text(face = "italic"),
    plot.title = ggplot2::element_text(size = 30, hjust = 0.5, face = "bold"),
    plot.subtitle = element_text(face = "italic", hjust = 0.5),
    text = element_text(size=20, face = "bold"),
  )
```